// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://knebskomwvvvoaclrwjv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImtuZWJza29td3Z2dm9hY2xyd2p2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk2MzkzMDMsImV4cCI6MjA2NTIxNTMwM30.45ggA2kNYAVa9_bRqL2ihaan1oqx55HyYlYLv_zxsa8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);